<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    

    <xacro:property name="stair_length" value="0.6" />
    <xacro:property name="stair_width" value="0.6" />
    <xacro:property name="stair_height" value="0.6" />

    <xacro:macro name="stairs" params="stairs xpos ypos zpos">

        <joint name="stair_joint_origin_${stairs}" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="base_link"/>
            <child link="stair_link_${stairs}"/>
        </joint>

        <link name="stair_link_${stairs}">
            <visual>
                <geometry>
                    <box size="${stair_length} ${stair_width} ${stair_height}"/>
                </geometry>
                <material name="grey"/>
                <origin rpy="0 0 0" xyz="${xpos} ${ypos} ${zpos}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${stair_length} ${stair_width} ${stair_height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="${xpos} ${ypos} ${zpos}"/>
            </collision>
            <inertial>
                <mass value="0.80"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
                <origin rpy="0 0 0" xyz="${xpos} ${ypos} ${zpos}"/>
            </inertial>
        </link>

        <xacro:if value="${stairs}">
            <xacro:stairs stairs="${stairs-1}" xpos="0" ypos="${ypos+stair_width/2}" zpos="${zpos/2+stair_height/2}"/>
            <joint name="stair_joint_${stairs}" type="fixed">
                <parent link="stair_link_${stairs}"/>
                <child link="stair_link_${stairs-1}"/>
            </joint>
        </xacro:if>

    </xacro:macro>

    <xacro:macro name="group_of_stairs" params="num xpos ypos zpos">
        <xacro:stairs stairs="${num}" xpos="0" ypos="0" zpos="${stair_height/2}"/>
    </xacro:macro>


</robot>