<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="stairs" params="stairs xpos ypos zpos stair_length stair_width stair_height">

        <joint name="stair_joint_origin_${stairs}" type="fixed">
            <origin rpy="0 0 -1.570795" xyz="0 0 0"/>
            <parent link="base_link"/>
            <child link="stair_link_${stairs}"/>
        </joint>

        <link name="stair_link_${stairs}">
            <visual>
                <geometry>
                    <box size="${stair_width} ${stair_length} ${zpos*2}"/>
                </geometry>
                <material name="grey"/>
                <origin rpy="0 0 0" xyz="${xpos} ${ypos} ${zpos}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${stair_width} ${stair_length} ${zpos*2}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="${xpos} ${ypos} ${zpos}"/>
            </collision>
            <inertial>
                <mass value="100"/>
                <inertia ixx="10" ixy="0" ixz="0" iyy="10" iyz="0" izz="1" />
                <origin rpy="0 0 0" xyz="${xpos} ${ypos} ${zpos}"/>
            </inertial>
        </link>
        
        <gazebo reference="stair_link_${stairs}">
            <mu1>0.1</mu1>
            <mu2>0.1</mu2>
        </gazebo>
        


        <xacro:if value="${stairs-1}">
            <xacro:stairs stairs="${stairs-1}" xpos="${stair_width/2}" ypos="${ypos+stair_length}" zpos="${zpos+stair_height/2}" stair_length="${stair_length}" stair_width="${stair_width}" stair_height="${stair_height}"/>
        </xacro:if>

    </xacro:macro>

    <xacro:macro name="group_of_stairs" params="num stair_width stair_length stair_height">
        <!--dummy base link-->
        <link name="base_link"/>
        <gazebo>
            <joint name ="weld" type="fixed">
                <parent>world</parent> 
                <child>base_link</child> <!-- put here the name of the base link -->
                <maxContacts>0</maxContacts>
            </joint> 
        </gazebo>
        <xacro:stairs stairs="${num}" xpos="${stair_width/2}" ypos="${stair_length/2}" zpos="${stair_height/2}" stair_length="${stair_length}" stair_width="${stair_width}" stair_height="${stair_height}"/>
    </xacro:macro>

</robot>